#Global settings
timezone: Europe/Vilnius
# Site settings
title: katmag
email: merezhnikova@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Čia reikia puslapio aprašymo.
  Tai padaryti faile _config.yml. Aprašymas naudojamas google paieškos
  rezultatuose.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://katmag.lt" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
